---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bhadrikaismy/public_html/blogs
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
